### ISSUE TITLE
Add authentication functionality

### ISSUE THREAD

**Issue by thechinedu** [thechinedu/calendoo#47]
### Tasks

- [x] Set up firebase local emulator
- [x] Set up firebase auth
- [ ] Add sign in page
- [ ] Add sign up page
- [ ] Add validation support to sign in page
- [ ] Add validation support to sign up page
- [ ] Integrate auth pages with firebase
- [ ] Add integration tests for sign in
- [ ] Add integration tests for sign up
- [ ] Add performance tests
- [ ] Add accessibility tests
